### PR TITLE
[BD-6]Add edx-when to upgrade Python requirements job.

### PR DESCRIPTION
**Pull request by ericfab179**
Update job that upgrades Python Requirements periodically adding repo that already complies with OEP-18.

**Reviewers**
- [x] @awais786 
- [x] @morenol
- [ ] @jmbowman

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ericfab179! I've created [OSPR-4449](https://openedx.atlassian.net/browse/OSPR-4449) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@ericfab179 Thank you for your contribution. Is this a Blended project PR?

**Comment by ericfab179** [comment]
@awais786 We think that this PR is ready to be merged.

**Comment by jmbowman** [comment]
It looks like we lost track of this one, and the code owners have changed since it was written.  @jmyatt , does someone on your team want to create a PR like this to periodically update the edx-when dependencies?

**Comment by jmyatt** [comment]
@jmbowman will do - you can close this one since it references Dave and Arch-BOM

**Pull request closed without merging**
