### PR TITLE
platform env renamed

### PR DESCRIPTION
**Pull request by jazibhumayun**
It gave error of file already exists with this name `platform_venv`. May be it was created from some virtual env, well to work around it I have renamed it and ran it multiple time it seems to working correct by renaming it to something different 

http://jenkins.analytics.edx.org/view/Exporter/job/analytics-email-optin-master/171/console
```
17:56:58 Running virtualenv with interpreter /usr/bin/python3.8
17:56:58 ERROR: File already exists and is not a directory.
```

### CODE REVIEW

**Comment by pwnage101** [comment]
I don't like the idea of having two nodes that are named `platform_virtualenv` and `platform_venv`, where one of them is a directory and the other is a file.  Can we name the file `platform_venv_path` and the directory `platform_venv`?

**Comment by jazibhumayun** [comment]
> I don't like the idea of having two nodes that are named `platform_virtualenv` and `platform_venv`, where one of them is a directory and the other is a file. Can we name the file `platform_venv_path` and the directory `platform_venv`?

Sorry, requires bit of clarity should I name it to  PLATFORM_VENV="platform_venv_path" ? or you are suggesting something different ? @pwnage101

**Comment by pwnage101** [comment]
I think:
```bash
PLATFORM_VENV="platform_venv"
```
and
```bash
echo "PLATFORM_VENV=${WORKSPACE}/${PLATFORM_VENV}" > platform_venv_path
```

**Comment by jazibhumayun** [comment]
Looking for thumb on this, this should be set to merge now, I did renaming as per suggestion and seed with branch, exporter email optin is working fine http://jenkins.analytics.edx.org/view/Exporter/job/analytics-email-optin-master/177/console

**Review by pwnage101 — APPROVED** [review]

**Pull request merged**
