### PR TITLE
Added Groovy scripts to aid local development

### PR DESCRIPTION
**Pull request by clintonb**
Two new scripts have been created to help developers create a credential
and a seed job. Both can be executed remotely rather than doing manual
tasks.

LEARNER-509

### CODE REVIEW

**Comment by clintonb** [comment]
@jibsheet Round 2!

FYI @edx/devops @edx/testeng

**Comment by clintonb** [comment]
@edx/testeng please review. I have found these scripts to be greatly beneficial for local development.

**Comment by clintonb** [comment]
@edx/testeng let me know if someone from your team can review, and when I can expect the review to be completed. It would be great to get this merged so developers can test their own jobs locally.

**Comment by jibsheet** [comment]
@clintonb I'm hoping to get to this on the tail end of my review, but am going to be slammed.  I am expecting to ask our intern Hannah to try using your branch as a naive user setting up their first jenkins docker container.  She's going to be working on that this week.

**Comment by estute** [comment]
@clintonb I'm reviewing this and should have some questions for you tomorrow

**Comment by hchen15** [comment]
@clintonb I ran the scripts and one problem I ran into was that the default tasks in your scripts included test; however not all the jobs have tests so that didn't work when I was building a sample job. Other than that, they worked

**Comment by clintonb** [comment]
@edx/devops @edx/testeng any interest in merging this? I can remove the test execution, if necessary, but I'd rather not go through the effort if this won't be merged.

**Comment by clintonb** [comment]
@edx/devops @edx/testeng I've received no feedback. 😢  Closing. If you need this in the future, feel free to pick it back up.

**Pull request closed without merging**
