### PR TITLE
[BD-6] Add configuration to upgrade Python requirements job.

### PR DESCRIPTION
**Pull request by ericfab179**
Update job that upgrades Python Requirements periodically adding repo that already complies with OEP-18.

**Reviewers**
- [ ] @awais786 
- [ ] @morenol

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ericfab179! I've created [OSPR-4462](https://openedx.atlassian.net/browse/OSPR-4462) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@ericfab179 Is this a BD PR?

**Comment by morenol** [comment]
Hi @natabene, all the PRs from @ericfab179 and me with the tag [BD-6] are from this blended project

**Comment by natabene** [comment]
@morenol Sorry, which tag do you mean?  Where can I find it in this PR?

**Comment by morenol** [comment]
> @morenol Sorry, which tag do you mean?  Where can I find it in this PR?

I'm sorry, I just noticed that this doesn't have a tag. @ericfab179 could you add the [BD-6] tag?

**Comment by natabene** [comment]
@morenol I will only ask for PRs that don't have BD-6 in the title.

**Comment by edx-webhook** [comment]
@ericfab179 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/jenkins-job-dsl&entry.867055334=https://github.com/edx/jenkins-job-dsl/pull/971&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-05+00:12&entry.1917517419=2020-05-11+12:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
