### PR TITLE
wip moving ecom jobs to public repo

### PR DESCRIPTION
**Pull request by e0d**
@jibsheet not as much as I had wanted, however, this will depend on the work you are doing to build a virtualenv for configuration and to be able to assume roles.

The original ECOM command definitions are here:

https://github.com/edx-ops/edx-jenkins-job-dsl/blob/master/src/main/groovy/org/edx/jenkins/dsl/Constants.groovy#L150

I think the definitions should be read in as secrets.

actual command run via ansible will look something like this for IDAs:

```
ansible all -i '10.0.0.235,' -u user -m shell -a '. /edx/app/discovery/discovery_env && sudo -E -u discovery /edx/app/discovery/venvs/discovery/bin/python /edx/app/discovery/discovery/manage.py refresh_course_metadata'
```

The corresponding command defined in the automated vars would be 

```
/edx/app/discovery/discovery_env && sudo -E -u discovery /edx/app/discovery/venvs/discovery/bin/python /edx/app/discovery/discovery/manage.py refresh_course_metadata
```

### CODE REVIEW

**Comment by jibsheet** [comment]
@e0d this is the run ansible piece, seed job coming shortly.  Commit messages have additional relevant context.

**Comment by jibsheet** [comment]
@e0d https://github.com/edx-ops/edx-jenkins-job-dsl/pull/48 is the seed job

We also need https://github.com/edx/configuration/pull/3384 to land

**Comment by e0d** [comment]
:+1:

**Comment by benpatterson** [comment]
Hey...just saw this. I'm wondering if you were planning on writing tests with it?

**Pull request merged**
