### PR TITLE
parameterize testeng-ci branch

### PR DESCRIPTION
**Pull request by estute**
@jzoldak @benpatterson 

this will fix broken eucalyptus test, because testeng-ci needs to be tagged/branched in relative lockstep with the edx-platform

### CODE REVIEW

**Comment by jzoldak** [comment]
Oh, that's what it was. Good find!
👍

**Comment by benpatterson** [comment]
:+1:

**Comment by estute** [comment]
@benpatterson in case you were curious...
The failing master tests were a side effect of the multi-scm plugin upgrade yesterday. Prior to the upgrade, the plugin offered one environment variable (GIT_COMMIT, which we use in the testeng-ci flow scripts) for storing information about the repos used by a job. This was part of why polling was not functioning correctly. The last clone within the scm section would be stored in this variable. However, the upgrade reversed this. The first repo cloned gets stored in GIT_COMMIT, and all subsequent repos cloned in the job get stored in GIT_COMMIT_1, GIT_COMMIT_2, etc.

**Comment by benpatterson** [comment]
Ok honestly this rings a bell. Sounds good to me.

**Pull request merged**
