### PR TITLE
Estute/move testeng dsls to open repo

### PR DESCRIPTION
**Pull request by estute**
@benpatterson @jzoldak 
If you could check this out when you get a chance.

### CODE REVIEW

**Comment by benpatterson** [comment]
It looks like this is failing on Travis. I'm guessing that Travis is defaulting to some other gradle installation that it ships with. Could you try uncommenting Akiva's comments on the .travis.yml file to see if that fixes it? If not, could you dig into it further?

**Comment by estute** [comment]
@benpatterson @jzoldak .gitignore was blocking jars from being pushed (hence the gradle failures). Fixed now.

**Comment by estute** [comment]
@jibsheet could you take a look at this?

**Comment by benpatterson** [comment]
👍 from me.

**Pull request merged**
