### PR TITLE
Setting schedule to mongo pruner jenkins job

### PR DESCRIPTION
**Pull request by nadeemshahzad**

### CODE REVIEW

**Comment by nadeemshahzad** [comment]
@edx/devops Please review

**Comment by feanil** [comment]
@nadeemshahzad none of the jobs have been manually run to prove that the currently work.  Shouldn't we do that before we turn on the schedule?

**Comment by nadeemshahzad** [comment]
@feanil Yes, I want to test these jobs running manually. We can hold this PR until we have tested all jobs.

**Comment by nadeemshahzad** [comment]
@feanil  All jobs are verified.Can we turn on the schedule?

**Pull request merged**
