### PR TITLE
Make whitelabel options the default for sandbox configuration

### PR DESCRIPTION
**Pull request by ibrahimahmed443**
This PR makes the Whitelabel sandbox settings the default settings on Sandbox creation page. Specifically, it checks ecommerce, ecommerce_worker and set_whitelabel flags.

### CODE REVIEW

**Comment by ibrahimahmed443** [comment]
@bill-filler FYI

**Comment by ibrahimahmed443** [comment]
@fredsmith can you please deploy this PR on sandbox page?

**Comment by fredsmith** [comment]
@ibrahimahmed443 FYI, there's some defaults missing that is causing this change to break sandbox builds when included by default. I reverted this change and re-seeded the job. Please provide functional defaults and re-submit.

**Comment by ibrahimahmed443** [comment]
@fredsmith @bill-filler The reason this failed was that the automated build does not have recreate checked. And in that case, dns_name is not passed on to the script as dns entries are not recreated. However, our script needs dns_name for creating sites, partners etc. Providing default dns_name in whitelabel playbook didn't solve the problem either because it recreated site entries in database, consequently we were getting MultipleObjectsReturned exception.

After doing some debugging, I came up with this PR: https://github.com/edx/configuration/pull/4462/files

The default sandbox creation is currently failing, so I was not able to test this extensively so far.

**Pull request merged**
