### PR TITLE
[BD-6] Add django-lang-pref-middleware to upgrade Python requirements job.

### PR DESCRIPTION
**Pull request by ericfab179**
Update job that upgrades Python Requirements periodically adding repo that already complies with OEP-18.

**Reviewers**
- [ ] @awais786 
- [x] @morenol

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @ericfab179! I've created [OSPR-4448](https://openedx.atlassian.net/browse/OSPR-4448) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jmbowman** [comment]
Yes, please add the team reviewer entry or we're not likely to notice when these PRs get created.

**Comment by natabene** [comment]
@ericfab179 Thank you for your contribution, is this a Blended project?

**Comment by morenol** [comment]
> @ericfab179 Thank you for your contribution, is this a Blended project?

Hi @natabene, yes. This is a blended project

**Comment by ericfab179** [comment]
@awais786 We think that this PR is ready to be merged.

**Comment by edx-webhook** [comment]
@ericfab179 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/jenkins-job-dsl&entry.867055334=https://github.com/edx/jenkins-job-dsl/pull/967&entry.1484655318=https://github.com/ericfab179&entry.752974735=2020-05-02+17:11&entry.1917517419=2020-05-20+16:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
