### PR TITLE
Disable Jenkins jobs for vertica upsize

### PR DESCRIPTION
**Pull request by brianhw**
for DENG-633

### CODE REVIEW

**Review by doctoryes — COMMENTED** [review]
Question: How do you know you've disabled *all* the jobs that read from/write to Vertica here?

**Comment by brianhw** [comment]
Fair question.   First, this only addresses those jobs that are seeded, so it doesn't address jobs that may be running that are outside of dsl.   I will be confirming that, but it's outside the scope of this PR.   Second, this started with those jobs that Troy identified last July, and included jobs that he missed in a first pass but were captured in code review.  Third, I then surveyed the remaining jobs to see if I knew of any that were added, or were otherwise missed last time.   (Two jobs have been removed since July, but I identified no jobs that needed to be added.)

**Review by doctoryes — APPROVED** [review]
I am satisfied with this answer. 😺

**Comment by brianhw** [comment]
I ran reseeding from this branch, and when done, reseeded from master.   So this branch is no longer necessary.

**Pull request closed without merging**
