### PR TITLE
Remove email notifications altogether in the worker CI job.

### PR DESCRIPTION
**Pull request by doctoryes**
Follow on PR to: https://github.com/edx/jenkins-job-dsl/pull/1339

### CODE REVIEW

**Comment by doctoryes** [comment]
@jazibhumayun If this PR is incorrect and emails are wanted upon failures, then feel free to close it.

**Comment by jazibhumayun** [comment]
Hey thanks for taking of care this in your on-call, I think we do need notification on this job failure. @doctoryes

**Comment by jazibhumayun** [comment]
I had raised this PR to rename the jobs with more descriptive names.
https://github.com/edx/jenkins-job-dsl/pull/1341

**Comment by doctoryes** [comment]
Closing - as these failures are intended to send email.

**Pull request closed without merging**
