### PR TITLE
updated description for sample job

### PR DESCRIPTION
**Pull request by hchen15**
instructions on how to build the seed/sample job

### CODE REVIEW

**Comment by feanil** [comment]
looks like the tests have failed on the repo?  Can you see what's going on and fix it before merging?

**Comment by jibsheet** [comment]
@hchen15 For context, codenarc is a code linter - I suspect you touched a file that had some things codenarc doesn't like and we added the file before we added codenarc.  You can run codenarc locally, or should be able to find more info in the travis logs.  @estute may have the most context on codenarc itself if you run into questions.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @hchen15! I've created [OSPR-2123](https://openedx.atlassian.net/browse/OSPR-2123) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/jenkins-job-dsl/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
Should this PR be kept open?

**Pull request closed without merging**
