### PR TITLE
fix: Update python virtualenv to 3.8 for mgmt cmds jobs

### PR DESCRIPTION
**Pull request by syedimranhassan**

### CODE REVIEW

**Review by adzuci — APPROVED** [review]
This may break some other jobs, but will likely fix the grader and enterprise ones so I think we should add a description and merge it.

**Comment by syedimranhassan** [comment]
I have tested it on xqueue, by running through my PR. It run successfully.
Here are the jobs
https://tools-edx-jenkins.edx.org/job/Seed%20Jobs/job/Xqueue%20Management%20Commands%20Seed%20Job/3108/console
https://tools-edx-jenkins.edx.org/job/xqueue/job/prod-edx-queued_submissions_to_cloudwatch/401214/console

**Comment by johnnagro** [comment]
our content job ran with success https://tools-edx-jenkins.edx.org/job/enterprise/job/prod-edx-transmit_content_metadata/194563/

i am trying the learner data job now

**Comment by johnnagro** [comment]
great success https://tools-edx-jenkins.edx.org/job/enterprise/job/prod-edx-transmit_learner_data/8667/

**Comment by johnnagro** [comment]
thank you @syedimranhassan @loucicchese @adzuci

**Pull request merged**
